apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3lNakExTURNMU5Wb1hEVE16TURjeE9UQTFNRE0xTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTS94CitGTHdRczRCM2oxZU5oYUNoN3R0OE5FZWNKZGxtTDRMcTIwbThmVDdidi9rU052c0NEODE5WENjcFFaT0YrNTIKRmdmTC83U1VWRjRCemtaT3VaWWd3cnRsUjNDQTkxNTBPKytDLzVjWWc1djF2THpvZlZPQmZjd2hUSHhiVjZ6MwpvYzcxd2RaUjZtTXNaa25wQ3B2WTNIRmpUV1Y4YVNYU2k2V0IrK2dwb3c1dHV1VXhXK1c1djdBTnpuZmtjZ2g4CllyanQ0M0Vjd1hhVjBHTXgvTnZDYWRhVlZPVTVjMUpzQW5rajhIaDRZdXFTMFJWbHBINVlYMjNHTG1YZXV2bHgKM1p3RmZQb2RISDVWSi90cEhNY1N5cGo1SlJscGhtQ2pkNmhwYVdJTmYvLzhBVlR4dzFidHY0Vm5ldktzR1dqOApudk5uMzYrZFFnTmV5RHJHNHNNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQdFBtZkVOdEJnbzJaWnpwOW9xSlJRRUpMZjRNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVcvZ1RyWENlT3locktmcjVwawp3MlVyTGZxU2I5czNxbk4yNUcyZ2drdGowK0QzbnZDcHV0TmVDcWVJaUVwM1pLcU9lNzZtMVQ3OVNDcm1wT0JWCnE5MEFFc3QwakhQMmxkQlpGMjlibUhUelAyYWkxL01qUzZ4VTEzZExZZi9uc2xPWHpjUGtGalFTNEJPc3dtWCsKdU5MdERXSWZZNHUwenFVaWxwWWJQWlloQk1BVEtySWJtMmxrWE5RK09McU1HM0h0MW41cW5rbW1adE53dUpBdgozRnN3TGpLdmkrazlKalJzaEtnMXJkM1hMb3pBQWxPSzBiSjVKakllZVAwUkpKVkdpZWYwOUlIT3NBNkQxelVVCmZvclpWczUza0xPZW95Y0pVVlZsSW9MbkVXVzA4MHloVXlJb0E1blp6UXFTQUxKbGVRSC9NWUx6dk9ibW5Dd0wKcGdzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://1817AF5522512F91C45D27C1123D1094.gr7.us-east-1.eks.amazonaws.com
  name: dev.us-east-1.eksctl.io
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3lNakExTURNMU5Wb1hEVE16TURjeE9UQTFNRE0xTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTS94CitGTHdRczRCM2oxZU5oYUNoN3R0OE5FZWNKZGxtTDRMcTIwbThmVDdidi9rU052c0NEODE5WENjcFFaT0YrNTIKRmdmTC83U1VWRjRCemtaT3VaWWd3cnRsUjNDQTkxNTBPKytDLzVjWWc1djF2THpvZlZPQmZjd2hUSHhiVjZ6MwpvYzcxd2RaUjZtTXNaa25wQ3B2WTNIRmpUV1Y4YVNYU2k2V0IrK2dwb3c1dHV1VXhXK1c1djdBTnpuZmtjZ2g4CllyanQ0M0Vjd1hhVjBHTXgvTnZDYWRhVlZPVTVjMUpzQW5rajhIaDRZdXFTMFJWbHBINVlYMjNHTG1YZXV2bHgKM1p3RmZQb2RISDVWSi90cEhNY1N5cGo1SlJscGhtQ2pkNmhwYVdJTmYvLzhBVlR4dzFidHY0Vm5ldktzR1dqOApudk5uMzYrZFFnTmV5RHJHNHNNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQdFBtZkVOdEJnbzJaWnpwOW9xSlJRRUpMZjRNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVcvZ1RyWENlT3locktmcjVwawp3MlVyTGZxU2I5czNxbk4yNUcyZ2drdGowK0QzbnZDcHV0TmVDcWVJaUVwM1pLcU9lNzZtMVQ3OVNDcm1wT0JWCnE5MEFFc3QwakhQMmxkQlpGMjlibUhUelAyYWkxL01qUzZ4VTEzZExZZi9uc2xPWHpjUGtGalFTNEJPc3dtWCsKdU5MdERXSWZZNHUwenFVaWxwWWJQWlloQk1BVEtySWJtMmxrWE5RK09McU1HM0h0MW41cW5rbW1adE53dUpBdgozRnN3TGpLdmkrazlKalJzaEtnMXJkM1hMb3pBQWxPSzBiSjVKakllZVAwUkpKVkdpZWYwOUlIT3NBNkQxelVVCmZvclpWczUza0xPZW95Y0pVVlZsSW9MbkVXVzA4MHloVXlJb0E1blp6UXFTQUxKbGVRSC9NWUx6dk9ibW5Dd0wKcGdzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://1817AF5522512F91C45D27C1123D1094.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:210994745537:cluster/dev
contexts:
- context:
    cluster: dev.us-east-1.eksctl.io
    user: k8s-admin@dev.us-east-1.eksctl.io
  name: k8s-admin@dev.us-east-1.eksctl.io
- context:
    cluster: arn:aws:eks:us-east-1:210994745537:cluster/dev
    user: arn:aws:eks:us-east-1:210994745537:cluster/dev
  name: arn:aws:eks:us-east-1:210994745537:cluster/dev
current-context: arn:aws:eks:us-east-1:210994745537:cluster/dev
kind: Config
preferences: {}
users:
- name: k8s-admin@dev.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - dev
      - --region
      - us-east-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
- name: arn:aws:eks:us-east-1:210994745537:cluster/dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - dev
      command: aws
